### ISSUE TITLE
M0 spi and M4 i2c not working together

### ISSUE THREAD

**Issue by joicetm** [schreinerman/Apollo3Blue_SoftwareExamples#1]
Hi,

I am using apollo 3 blue for our new product and i have started the software  development for the same.
I am using release AmbiqSuite-Rel2.2.0 for my development and tested some of the basic features and it looks really good. but i am a little concerned about the support and depth of the provided sdk.

Do you have any means of support/forum to discuss the bugs and issues of the sdk and controller ?

I am having a small issue while trying to configure i2c and spi together and after little debug, i have found that configuring the m4 scl pin (gpio 39) and m0 spi miso(gpio pin 6) causes to crash the code. (independently both of them works as expected)
where can i raise these kind of issues ?

If it is not the right place for this question, please ignore.

**Comment by schreinerman** [comment]
Please raise this issue at support@ambiqmicro.com

At http://ambiqmicro.com there is also a frequently asked questions forum.

This repository is not from Ambiq Micro and is also not using the AmbiqSuite. See also the LICENSE.md file.

**Comment by joicetm** [comment]
Hi schreinerman,

Thanks for the update and sorry for posting it here.
You may please delete this issue.
